services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - SOLR_URL=${SOLR_URL}
    volumes:
      - .:/rails
    depends_on:
      solr:
        condition: service_healthy
    networks:
      - app_network

  solr:
    # https://solr.apache.org/guide/solr/latest/deployment-guide/solr-in-docker.html#docker-compose
    image: solr:9
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
    command:
      - solr-precreate
      - development-core
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS --connect-timeout 2 --max-time 2 http://localhost:8983/solr/development-core/admin/ping?wt=json | grep -q '\"status\":\"OK\"'"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s
    networks:
      - app_network

volumes:
  solr_data:

networks:
  app_network:
    driver: bridge
