version: 2.1

orbs:
  ruby: circleci/ruby@2.1.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.4-browsers
        environment:
          RAILS_ENV: test
          SOLR_URL: http://localhost:8983/solr/blacklight-core
      - image: solr:9.6.1
        name: solr
        environment:
          SOLR_HOME: /var/solr/data
    steps:
      - checkout
      - run:
          name: Which directory?
          command: pwd
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - run:
          name: Copy Solr Configuration
          command: |
            docker cp solr/conf/. solr:/var/solr/data/config
      - run:
          name: Create Solr Core
          command: |
            docker exec solr solr create -c blacklight-core -d /var/solr/data/config
      - run:
          name: Wait for Solr
          command: |
            until curl -s "http://localhost:8983/solr/admin/ping" | grep -q '"status":"OK"'; do
              echo "Waiting for Solr..."
              sleep 5
            done
      - run:
          name: Test suite
          command: bundle exec rake

workflows:
  test:
    jobs:
      - build
