version: 2.1

orbs:
  ruby: circleci/ruby@2.1.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.4-browsers

    steps:
      - checkout
      - restore_cache:
          keys:
            - solr-tgz-cache-{{ checksum "tmp/solr-9.6.1.tgz" }}
            - solr-tgz-cache-{{ .Branch }}
            - solr-tgz-cache-

      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - run:
          name: Test suite
          command: bundle exec rake sc:test
      - save_cache:
          paths:
            - tmp/solr-9.6.1.tgz
          key: solr-tgz-cache-{{ checksum "tmp/solr-9.6.1.tgz" }}

      - store_artifacts:
          path: tmp/capybara

workflows:
  build:
    jobs:
      - build
