version: 2.1

orbs:
  ruby: circleci/ruby@2.1.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.4-browsers
      - image: solr:9.6.1
        environment:
          - SOLR_HOME=/var/solr
          - SOLR_CORE=test-core

    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - run:
          name: Copy Solr configuration
          command: |
            docker cp ./solr/conf solr:/opt/solr/server/solr/test-core
      - run:
          name: Set up Solr core
          command: |
            docker exec -t solr bin/solr create_core -c test-core
      - run:
          name: Test suite
          command: bundle exec rake spec
      - store_artifacts:
          path: tmp/capybara

workflows:
  test:
    jobs:
      - build
