# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  # See the Ruby orb documentation here: https://circleci.com/developer/orbs/orb/circleci/ruby
  ruby: circleci/ruby@2.5.4

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build_and_test:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/ruby
      - image: cimg/ruby:3.3.4-browsers

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - restore_cache:
          keys:
            - solr-tgz-cache-{{ checksum ".solr_wrapper.yml" }}
            - solr-tgz-cache-{{ .Branch }}
            - solr-tgz-cache-

      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - run:
          name: Test suite
          command: bundle exec rake sc:test
      - save_cache:
          key: solr-tgz-cache-{{ checksum ".solr_wrapper.yml" }}
          paths:
            - tmp/solr-9.6.1.tgz

      - store_artifacts:
          path: tmp/capybara
      - setup_remote_docker
      - run:
          name: Build Playwright stack
          command: docker compose build app solr solr-fixtures playwright
      - run:
          name: Run Playwright tests
          command: |
            docker compose up playwright
      - run:
          name: Collect Playwright artifacts
          when: always
          command: |
            mkdir -p e2e/test-results
            docker cp playwright-e2e-run:/e2e/test-results/. e2e/test-results 2>/dev/null || echo "No test results."
      - store_artifacts:
          path: e2e/test-results

workflows:
  ci:
    jobs:
      - build_and_test
