version: 2.1

orbs:
  ruby: circleci/ruby@2.1.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.3.4-browsers
        environment:
          RAILS_ENV: test
          SOLR_URL: http://localhost:8983/solr/blacklight_core
      - image: solr:9.6.1
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - run:
          name: Test suite
          command: bundle exec rake sc:test

workflows:
  test:
    jobs:
      - build
